`default_nettype none

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE
module Twiddle_Storage (
    output logic signed[16 * 16 - 1:0] real_twiddles,
    output logic signed[16 * 16 - 1:0] imag_twiddles
);

assign real_twiddles[15:0] = 16'b0000001111101000;
assign real_twiddles[31:16] = 16'b0000001111010101;
assign real_twiddles[47:32] = 16'b0000001110011100;
assign real_twiddles[63:48] = 16'b0000001101000000;
assign real_twiddles[79:64] = 16'b0000001011000100;
assign real_twiddles[95:80] = 16'b0000001000101100;
assign real_twiddles[111:96] = 16'b0000000101111111;
assign real_twiddles[127:112] = 16'b0000000011000100;
assign real_twiddles[143:128] = 16'b0000000000000001;
assign real_twiddles[159:144] = 16'b1111111100111101;
assign real_twiddles[175:160] = 16'b1111111010000010;
assign real_twiddles[191:176] = 16'b1111110111010101;
assign real_twiddles[207:192] = 16'b1111110100111101;
assign real_twiddles[223:208] = 16'b1111110011000001;
assign real_twiddles[239:224] = 16'b1111110001100101;
assign real_twiddles[255:240] = 16'b1111110000101100;
 

assign imag_twiddles[15:0] = 16'b0000000000000000;
assign imag_twiddles[31:16] = 16'b1111111100111101;
assign imag_twiddles[47:32] = 16'b1111111010000010;
assign imag_twiddles[63:48] = 16'b1111110111010101;
assign imag_twiddles[79:64] = 16'b1111110100111101;
assign imag_twiddles[95:80] = 16'b1111110011000001;
assign imag_twiddles[111:96] = 16'b1111110001100101;
assign imag_twiddles[127:112] = 16'b1111110000101100;
assign imag_twiddles[143:128] = 16'b1111110000011000;
assign imag_twiddles[159:144] = 16'b1111110000101100;
assign imag_twiddles[175:160] = 16'b1111110001100101;
assign imag_twiddles[191:176] = 16'b1111110011000001;
assign imag_twiddles[207:192] = 16'b1111110100111101;
assign imag_twiddles[223:208] = 16'b1111110111010101;
assign imag_twiddles[239:224] = 16'b1111111010000010;
assign imag_twiddles[255:240] = 16'b1111111100111101;


endmodule