`default_nettype none

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE
module Twiddle_Storage (
    output logic signed[16 - 1:0] real_twiddles,
    output logic signed[16 - 1:0] imag_twiddles
);

reg signed[16 * 32 - 1:0] real_twiddle_register;
reg signed[16 * 32 - 1:0] imag_twiddle_register;

assign real_twiddle_register[15:0] = 16'b0000001111101000;
assign real_twiddle_register[31:16] = 16'b0000001111010101;
assign real_twiddle_register[47:32] = 16'b0000001110011100;
assign real_twiddle_register[63:48] = 16'b0000001101000000;
assign real_twiddle_register[79:64] = 16'b0000001011000100;
assign real_twiddle_register[95:80] = 16'b0000001000101100;
assign real_twiddle_register[111:96] = 16'b0000000101111111;
assign real_twiddle_register[127:112] = 16'b0000000011000100;
assign real_twiddle_register[143:128] = 16'b0000000000000001;
assign real_twiddle_register[159:144] = 16'b1111111100111101;
assign real_twiddle_register[175:160] = 16'b1111111010000010;
assign real_twiddle_register[191:176] = 16'b1111110111010101;
assign real_twiddle_register[207:192] = 16'b1111110100111101;
assign real_twiddle_register[223:208] = 16'b1111110011000001;
assign real_twiddle_register[239:224] = 16'b1111110001100101;
assign real_twiddle_register[255:240] = 16'b1111110000101100;
assign real_twiddle_register[271:256] = 16'b1111110000011000;
assign real_twiddle_register[287:272] = 16'b1111110000101100;
assign real_twiddle_register[303:288] = 16'b1111110001100101;
assign real_twiddle_register[319:304] = 16'b1111110011000001;
assign real_twiddle_register[335:320] = 16'b1111110100111101;
assign real_twiddle_register[351:336] = 16'b1111110111010101;
assign real_twiddle_register[367:352] = 16'b1111111010000010;
assign real_twiddle_register[383:368] = 16'b1111111100111101;
assign real_twiddle_register[399:384] = 16'b0000000000000000;
assign real_twiddle_register[415:400] = 16'b0000000011000100;
assign real_twiddle_register[431:416] = 16'b0000000101111111;
assign real_twiddle_register[447:432] = 16'b0000001000101100;
assign real_twiddle_register[463:448] = 16'b0000001011000100;
assign real_twiddle_register[479:464] = 16'b0000001101000000;
assign real_twiddle_register[495:480] = 16'b0000001110011100;
assign real_twiddle_register[511:496] = 16'b0000001111010101;
 

assign imag_twiddle_register[15:0] = 16'b0000000000000000;
assign imag_twiddle_register[31:16] = 16'b1111111100111101;
assign imag_twiddle_register[47:32] = 16'b1111111010000010;
assign imag_twiddle_register[63:48] = 16'b1111110111010101;
assign imag_twiddle_register[79:64] = 16'b1111110100111101;
assign imag_twiddle_register[95:80] = 16'b1111110011000001;
assign imag_twiddle_register[111:96] = 16'b1111110001100101;
assign imag_twiddle_register[127:112] = 16'b1111110000101100;
assign imag_twiddle_register[143:128] = 16'b1111110000011000;
assign imag_twiddle_register[159:144] = 16'b1111110000101100;
assign imag_twiddle_register[175:160] = 16'b1111110001100101;
assign imag_twiddle_register[191:176] = 16'b1111110011000001;
assign imag_twiddle_register[207:192] = 16'b1111110100111101;
assign imag_twiddle_register[223:208] = 16'b1111110111010101;
assign imag_twiddle_register[239:224] = 16'b1111111010000010;
assign imag_twiddle_register[255:240] = 16'b1111111100111101;
assign imag_twiddle_register[271:256] = 16'b0000000000000000;
assign imag_twiddle_register[287:272] = 16'b0000000011000100;
assign imag_twiddle_register[303:288] = 16'b0000000101111111;
assign imag_twiddle_register[319:304] = 16'b0000001000101100;
assign imag_twiddle_register[335:320] = 16'b0000001011000100;
assign imag_twiddle_register[351:336] = 16'b0000001101000000;
assign imag_twiddle_register[367:352] = 16'b0000001110011100;
assign imag_twiddle_register[383:368] = 16'b0000001111010101;
assign imag_twiddle_register[399:384] = 16'b0000001111101000;
assign imag_twiddle_register[415:400] = 16'b0000001111010101;
assign imag_twiddle_register[431:416] = 16'b0000001110011100;
assign imag_twiddle_register[447:432] = 16'b0000001101000000;
assign imag_twiddle_register[463:448] = 16'b0000001011000100;
assign imag_twiddle_register[479:464] = 16'b0000001000101100;
assign imag_twiddle_register[495:480] = 16'b0000000101111111;
assign imag_twiddle_register[511:496] = 16'b0000000011000100;


endmodule