`default_nettype none

`ifndef twiddle
`define twiddle

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE
module Twiddle_Storage (
    output logic signed[{{ twiddle_size }} * {{ num_twiddles }} - 1:0] real_twiddles,
    output logic signed[{{ twiddle_size }} * {{ num_twiddles }} - 1:0] imag_twiddles
);

{{real_twiddles}} 

{{imag_twiddles}}

endmodule

`endif