`default_nettype none

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE

//-----------------------------------------------------------------------------
//  File       : twiddle.sv
//  Author     : Michael Ray
//  Created    : <2025-04-20>
//  Description: 
//      Stores the twiddle factors for an n point radix 2 fft
//
//  Parameters: None 
//
//  Ports:
//      Outputs:
//          - real_twiddles : array representing real components of twiddle factors
//          - imag_twiddles : array representing imaginary components of twiddle factors
//
//  Notes:
//      Do not attempt to modify this file. It was generated by the python script in the build module, "build.py"
//
//-----------------------------------------------------------------------------
module Twiddle_Storage_64 (
    output logic signed[16 * 32 - 1:0] real_twiddles,
    output logic signed[16 * 32 - 1:0] imag_twiddles
);

assign real_twiddles[15:0] = 16'b0000001111101000;
assign real_twiddles[31:16] = 16'b0000001111100100;
assign real_twiddles[47:32] = 16'b0000001111010101;
assign real_twiddles[63:48] = 16'b0000001110111101;
assign real_twiddles[79:64] = 16'b0000001110011100;
assign real_twiddles[95:80] = 16'b0000001101110010;
assign real_twiddles[111:96] = 16'b0000001101000000;
assign real_twiddles[127:112] = 16'b0000001100000110;
assign real_twiddles[143:128] = 16'b0000001011000100;
assign real_twiddles[159:144] = 16'b0000001001111011;
assign real_twiddles[175:160] = 16'b0000001000101100;
assign real_twiddles[191:176] = 16'b0000000111011000;
assign real_twiddles[207:192] = 16'b0000000101111111;
assign real_twiddles[223:208] = 16'b0000000100100011;
assign real_twiddles[239:224] = 16'b0000000011000100;
assign real_twiddles[255:240] = 16'b0000000001100011;
assign real_twiddles[271:256] = 16'b0000000000000000;
assign real_twiddles[287:272] = 16'b1111111110011110;
assign real_twiddles[303:288] = 16'b1111111100111101;
assign real_twiddles[319:304] = 16'b1111111011011110;
assign real_twiddles[335:320] = 16'b1111111010000010;
assign real_twiddles[351:336] = 16'b1111111000101001;
assign real_twiddles[367:352] = 16'b1111110111010101;
assign real_twiddles[383:368] = 16'b1111110110000110;
assign real_twiddles[399:384] = 16'b1111110100111101;
assign real_twiddles[415:400] = 16'b1111110011111011;
assign real_twiddles[431:416] = 16'b1111110011000001;
assign real_twiddles[447:432] = 16'b1111110010001111;
assign real_twiddles[463:448] = 16'b1111110001100101;
assign real_twiddles[479:464] = 16'b1111110001000100;
assign real_twiddles[495:480] = 16'b1111110000101100;
assign real_twiddles[511:496] = 16'b1111110000011101;
 

assign imag_twiddles[15:0] = 16'b0000000000000000;
assign imag_twiddles[31:16] = 16'b1111111110011110;
assign imag_twiddles[47:32] = 16'b1111111100111101;
assign imag_twiddles[63:48] = 16'b1111111011011110;
assign imag_twiddles[79:64] = 16'b1111111010000010;
assign imag_twiddles[95:80] = 16'b1111111000101001;
assign imag_twiddles[111:96] = 16'b1111110111010101;
assign imag_twiddles[127:112] = 16'b1111110110000110;
assign imag_twiddles[143:128] = 16'b1111110100111101;
assign imag_twiddles[159:144] = 16'b1111110011111011;
assign imag_twiddles[175:160] = 16'b1111110011000001;
assign imag_twiddles[191:176] = 16'b1111110010001111;
assign imag_twiddles[207:192] = 16'b1111110001100101;
assign imag_twiddles[223:208] = 16'b1111110001000100;
assign imag_twiddles[239:224] = 16'b1111110000101100;
assign imag_twiddles[255:240] = 16'b1111110000011101;
assign imag_twiddles[271:256] = 16'b1111110000011000;
assign imag_twiddles[287:272] = 16'b1111110000011101;
assign imag_twiddles[303:288] = 16'b1111110000101100;
assign imag_twiddles[319:304] = 16'b1111110001000100;
assign imag_twiddles[335:320] = 16'b1111110001100101;
assign imag_twiddles[351:336] = 16'b1111110010001111;
assign imag_twiddles[367:352] = 16'b1111110011000001;
assign imag_twiddles[383:368] = 16'b1111110011111011;
assign imag_twiddles[399:384] = 16'b1111110100111101;
assign imag_twiddles[415:400] = 16'b1111110110000110;
assign imag_twiddles[431:416] = 16'b1111110111010101;
assign imag_twiddles[447:432] = 16'b1111111000101001;
assign imag_twiddles[463:448] = 16'b1111111010000010;
assign imag_twiddles[479:464] = 16'b1111111011011110;
assign imag_twiddles[495:480] = 16'b1111111100111101;
assign imag_twiddles[511:496] = 16'b1111111110011110;


endmodule