`default_nettype none

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE

//-----------------------------------------------------------------------------
//  File       : twiddle.sv
//  Author     : Michael Ray
//  Created    : <2025-04-20>
//  Description: 
//      Stores the twiddle factors for an n point radix 2 fft
//
//  Parameters: None 
//
//  Ports:
//      Outputs:
//          - real_twiddles : array representing real components of twiddle factors
//          - imag_twiddles : array representing imaginary components of twiddle factors
//
//  Notes:
//      Do not attempt to modify this file. It was generated by the python script in the build module, "build.py"
//
//-----------------------------------------------------------------------------
module Twiddle_Storage_256 (
    output logic signed[16 * 128 - 1:0] real_twiddles,
    output logic signed[16 * 128 - 1:0] imag_twiddles
);

assign real_twiddles[15:0] = 16'b0000001111101000;
assign real_twiddles[31:16] = 16'b0000001111101000;
assign real_twiddles[47:32] = 16'b0000001111100111;
assign real_twiddles[63:48] = 16'b0000001111100110;
assign real_twiddles[79:64] = 16'b0000001111100100;
assign real_twiddles[95:80] = 16'b0000001111100001;
assign real_twiddles[111:96] = 16'b0000001111011110;
assign real_twiddles[127:112] = 16'b0000001111011010;
assign real_twiddles[143:128] = 16'b0000001111010101;
assign real_twiddles[159:144] = 16'b0000001111010000;
assign real_twiddles[175:160] = 16'b0000001111001011;
assign real_twiddles[191:176] = 16'b0000001111000100;
assign real_twiddles[207:192] = 16'b0000001110111101;
assign real_twiddles[223:208] = 16'b0000001110110110;
assign real_twiddles[239:224] = 16'b0000001110101110;
assign real_twiddles[255:240] = 16'b0000001110100101;
assign real_twiddles[271:256] = 16'b0000001110011100;
assign real_twiddles[287:272] = 16'b0000001110010011;
assign real_twiddles[303:288] = 16'b0000001110001000;
assign real_twiddles[319:304] = 16'b0000001101111110;
assign real_twiddles[335:320] = 16'b0000001101110010;
assign real_twiddles[351:336] = 16'b0000001101100111;
assign real_twiddles[367:352] = 16'b0000001101011010;
assign real_twiddles[383:368] = 16'b0000001101001101;
assign real_twiddles[399:384] = 16'b0000001101000000;
assign real_twiddles[415:400] = 16'b0000001100110010;
assign real_twiddles[431:416] = 16'b0000001100100100;
assign real_twiddles[447:432] = 16'b0000001100010101;
assign real_twiddles[463:448] = 16'b0000001100000110;
assign real_twiddles[479:464] = 16'b0000001011110110;
assign real_twiddles[495:480] = 16'b0000001011100101;
assign real_twiddles[511:496] = 16'b0000001011010101;
assign real_twiddles[527:512] = 16'b0000001011000100;
assign real_twiddles[543:528] = 16'b0000001010110010;
assign real_twiddles[559:544] = 16'b0000001010100000;
assign real_twiddles[575:560] = 16'b0000001010001110;
assign real_twiddles[591:576] = 16'b0000001001111011;
assign real_twiddles[607:592] = 16'b0000001001101000;
assign real_twiddles[623:608] = 16'b0000001001010100;
assign real_twiddles[639:624] = 16'b0000001001000000;
assign real_twiddles[655:640] = 16'b0000001000101100;
assign real_twiddles[671:656] = 16'b0000001000010111;
assign real_twiddles[687:672] = 16'b0000001000000011;
assign real_twiddles[703:688] = 16'b0000000111101101;
assign real_twiddles[719:704] = 16'b0000000111011000;
assign real_twiddles[735:720] = 16'b0000000111000010;
assign real_twiddles[751:736] = 16'b0000000110101100;
assign real_twiddles[767:752] = 16'b0000000110010110;
assign real_twiddles[783:768] = 16'b0000000101111111;
assign real_twiddles[799:784] = 16'b0000000101101000;
assign real_twiddles[815:800] = 16'b0000000101010001;
assign real_twiddles[831:816] = 16'b0000000100111010;
assign real_twiddles[847:832] = 16'b0000000100100011;
assign real_twiddles[863:848] = 16'b0000000100001011;
assign real_twiddles[879:864] = 16'b0000000011110011;
assign real_twiddles[895:880] = 16'b0000000011011100;
assign real_twiddles[911:896] = 16'b0000000011000100;
assign real_twiddles[927:912] = 16'b0000000010101011;
assign real_twiddles[943:928] = 16'b0000000010010011;
assign real_twiddles[959:944] = 16'b0000000001111011;
assign real_twiddles[975:960] = 16'b0000000001100011;
assign real_twiddles[991:976] = 16'b0000000001001010;
assign real_twiddles[1007:992] = 16'b0000000000110010;
assign real_twiddles[1023:1008] = 16'b0000000000011001;
assign real_twiddles[1039:1024] = 16'b0000000000000000;
assign real_twiddles[1055:1040] = 16'b1111111111101000;
assign real_twiddles[1071:1056] = 16'b1111111111001111;
assign real_twiddles[1087:1072] = 16'b1111111110110111;
assign real_twiddles[1103:1088] = 16'b1111111110011110;
assign real_twiddles[1119:1104] = 16'b1111111110000110;
assign real_twiddles[1135:1120] = 16'b1111111101101110;
assign real_twiddles[1151:1136] = 16'b1111111101010110;
assign real_twiddles[1167:1152] = 16'b1111111100111101;
assign real_twiddles[1183:1168] = 16'b1111111100100101;
assign real_twiddles[1199:1184] = 16'b1111111100001110;
assign real_twiddles[1215:1200] = 16'b1111111011110110;
assign real_twiddles[1231:1216] = 16'b1111111011011110;
assign real_twiddles[1247:1232] = 16'b1111111011000111;
assign real_twiddles[1263:1248] = 16'b1111111010110000;
assign real_twiddles[1279:1264] = 16'b1111111010011001;
assign real_twiddles[1295:1280] = 16'b1111111010000010;
assign real_twiddles[1311:1296] = 16'b1111111001101011;
assign real_twiddles[1327:1312] = 16'b1111111001010101;
assign real_twiddles[1343:1328] = 16'b1111111000111111;
assign real_twiddles[1359:1344] = 16'b1111111000101001;
assign real_twiddles[1375:1360] = 16'b1111111000010100;
assign real_twiddles[1391:1376] = 16'b1111110111111110;
assign real_twiddles[1407:1392] = 16'b1111110111101010;
assign real_twiddles[1423:1408] = 16'b1111110111010101;
assign real_twiddles[1439:1424] = 16'b1111110111000001;
assign real_twiddles[1455:1440] = 16'b1111110110101101;
assign real_twiddles[1471:1456] = 16'b1111110110011001;
assign real_twiddles[1487:1472] = 16'b1111110110000110;
assign real_twiddles[1503:1488] = 16'b1111110101110011;
assign real_twiddles[1519:1504] = 16'b1111110101100001;
assign real_twiddles[1535:1520] = 16'b1111110101001111;
assign real_twiddles[1551:1536] = 16'b1111110100111101;
assign real_twiddles[1567:1552] = 16'b1111110100101100;
assign real_twiddles[1583:1568] = 16'b1111110100011100;
assign real_twiddles[1599:1584] = 16'b1111110100001011;
assign real_twiddles[1615:1600] = 16'b1111110011111011;
assign real_twiddles[1631:1616] = 16'b1111110011101100;
assign real_twiddles[1647:1632] = 16'b1111110011011101;
assign real_twiddles[1663:1648] = 16'b1111110011001111;
assign real_twiddles[1679:1664] = 16'b1111110011000001;
assign real_twiddles[1695:1680] = 16'b1111110010110100;
assign real_twiddles[1711:1696] = 16'b1111110010100111;
assign real_twiddles[1727:1712] = 16'b1111110010011010;
assign real_twiddles[1743:1728] = 16'b1111110010001111;
assign real_twiddles[1759:1744] = 16'b1111110010000011;
assign real_twiddles[1775:1760] = 16'b1111110001111001;
assign real_twiddles[1791:1776] = 16'b1111110001101110;
assign real_twiddles[1807:1792] = 16'b1111110001100101;
assign real_twiddles[1823:1808] = 16'b1111110001011100;
assign real_twiddles[1839:1824] = 16'b1111110001010011;
assign real_twiddles[1855:1840] = 16'b1111110001001011;
assign real_twiddles[1871:1856] = 16'b1111110001000100;
assign real_twiddles[1887:1872] = 16'b1111110000111101;
assign real_twiddles[1903:1888] = 16'b1111110000110110;
assign real_twiddles[1919:1904] = 16'b1111110000110001;
assign real_twiddles[1935:1920] = 16'b1111110000101100;
assign real_twiddles[1951:1936] = 16'b1111110000100111;
assign real_twiddles[1967:1952] = 16'b1111110000100011;
assign real_twiddles[1983:1968] = 16'b1111110000100000;
assign real_twiddles[1999:1984] = 16'b1111110000011101;
assign real_twiddles[2015:2000] = 16'b1111110000011011;
assign real_twiddles[2031:2016] = 16'b1111110000011010;
assign real_twiddles[2047:2032] = 16'b1111110000011001;
 

assign imag_twiddles[15:0] = 16'b0000000000000000;
assign imag_twiddles[31:16] = 16'b1111111111101000;
assign imag_twiddles[47:32] = 16'b1111111111001111;
assign imag_twiddles[63:48] = 16'b1111111110110111;
assign imag_twiddles[79:64] = 16'b1111111110011110;
assign imag_twiddles[95:80] = 16'b1111111110000110;
assign imag_twiddles[111:96] = 16'b1111111101101110;
assign imag_twiddles[127:112] = 16'b1111111101010110;
assign imag_twiddles[143:128] = 16'b1111111100111101;
assign imag_twiddles[159:144] = 16'b1111111100100101;
assign imag_twiddles[175:160] = 16'b1111111100001110;
assign imag_twiddles[191:176] = 16'b1111111011110110;
assign imag_twiddles[207:192] = 16'b1111111011011110;
assign imag_twiddles[223:208] = 16'b1111111011000111;
assign imag_twiddles[239:224] = 16'b1111111010110000;
assign imag_twiddles[255:240] = 16'b1111111010011001;
assign imag_twiddles[271:256] = 16'b1111111010000010;
assign imag_twiddles[287:272] = 16'b1111111001101011;
assign imag_twiddles[303:288] = 16'b1111111001010101;
assign imag_twiddles[319:304] = 16'b1111111000111111;
assign imag_twiddles[335:320] = 16'b1111111000101001;
assign imag_twiddles[351:336] = 16'b1111111000010100;
assign imag_twiddles[367:352] = 16'b1111110111111110;
assign imag_twiddles[383:368] = 16'b1111110111101010;
assign imag_twiddles[399:384] = 16'b1111110111010101;
assign imag_twiddles[415:400] = 16'b1111110111000001;
assign imag_twiddles[431:416] = 16'b1111110110101101;
assign imag_twiddles[447:432] = 16'b1111110110011001;
assign imag_twiddles[463:448] = 16'b1111110110000110;
assign imag_twiddles[479:464] = 16'b1111110101110011;
assign imag_twiddles[495:480] = 16'b1111110101100001;
assign imag_twiddles[511:496] = 16'b1111110101001111;
assign imag_twiddles[527:512] = 16'b1111110100111101;
assign imag_twiddles[543:528] = 16'b1111110100101100;
assign imag_twiddles[559:544] = 16'b1111110100011100;
assign imag_twiddles[575:560] = 16'b1111110100001011;
assign imag_twiddles[591:576] = 16'b1111110011111011;
assign imag_twiddles[607:592] = 16'b1111110011101100;
assign imag_twiddles[623:608] = 16'b1111110011011101;
assign imag_twiddles[639:624] = 16'b1111110011001111;
assign imag_twiddles[655:640] = 16'b1111110011000001;
assign imag_twiddles[671:656] = 16'b1111110010110100;
assign imag_twiddles[687:672] = 16'b1111110010100111;
assign imag_twiddles[703:688] = 16'b1111110010011010;
assign imag_twiddles[719:704] = 16'b1111110010001111;
assign imag_twiddles[735:720] = 16'b1111110010000011;
assign imag_twiddles[751:736] = 16'b1111110001111001;
assign imag_twiddles[767:752] = 16'b1111110001101110;
assign imag_twiddles[783:768] = 16'b1111110001100101;
assign imag_twiddles[799:784] = 16'b1111110001011100;
assign imag_twiddles[815:800] = 16'b1111110001010011;
assign imag_twiddles[831:816] = 16'b1111110001001011;
assign imag_twiddles[847:832] = 16'b1111110001000100;
assign imag_twiddles[863:848] = 16'b1111110000111101;
assign imag_twiddles[879:864] = 16'b1111110000110110;
assign imag_twiddles[895:880] = 16'b1111110000110001;
assign imag_twiddles[911:896] = 16'b1111110000101100;
assign imag_twiddles[927:912] = 16'b1111110000100111;
assign imag_twiddles[943:928] = 16'b1111110000100011;
assign imag_twiddles[959:944] = 16'b1111110000100000;
assign imag_twiddles[975:960] = 16'b1111110000011101;
assign imag_twiddles[991:976] = 16'b1111110000011011;
assign imag_twiddles[1007:992] = 16'b1111110000011010;
assign imag_twiddles[1023:1008] = 16'b1111110000011001;
assign imag_twiddles[1039:1024] = 16'b1111110000011000;
assign imag_twiddles[1055:1040] = 16'b1111110000011001;
assign imag_twiddles[1071:1056] = 16'b1111110000011010;
assign imag_twiddles[1087:1072] = 16'b1111110000011011;
assign imag_twiddles[1103:1088] = 16'b1111110000011101;
assign imag_twiddles[1119:1104] = 16'b1111110000100000;
assign imag_twiddles[1135:1120] = 16'b1111110000100011;
assign imag_twiddles[1151:1136] = 16'b1111110000100111;
assign imag_twiddles[1167:1152] = 16'b1111110000101100;
assign imag_twiddles[1183:1168] = 16'b1111110000110001;
assign imag_twiddles[1199:1184] = 16'b1111110000110110;
assign imag_twiddles[1215:1200] = 16'b1111110000111101;
assign imag_twiddles[1231:1216] = 16'b1111110001000100;
assign imag_twiddles[1247:1232] = 16'b1111110001001011;
assign imag_twiddles[1263:1248] = 16'b1111110001010011;
assign imag_twiddles[1279:1264] = 16'b1111110001011100;
assign imag_twiddles[1295:1280] = 16'b1111110001100101;
assign imag_twiddles[1311:1296] = 16'b1111110001101110;
assign imag_twiddles[1327:1312] = 16'b1111110001111001;
assign imag_twiddles[1343:1328] = 16'b1111110010000011;
assign imag_twiddles[1359:1344] = 16'b1111110010001111;
assign imag_twiddles[1375:1360] = 16'b1111110010011010;
assign imag_twiddles[1391:1376] = 16'b1111110010100111;
assign imag_twiddles[1407:1392] = 16'b1111110010110100;
assign imag_twiddles[1423:1408] = 16'b1111110011000001;
assign imag_twiddles[1439:1424] = 16'b1111110011001111;
assign imag_twiddles[1455:1440] = 16'b1111110011011101;
assign imag_twiddles[1471:1456] = 16'b1111110011101100;
assign imag_twiddles[1487:1472] = 16'b1111110011111011;
assign imag_twiddles[1503:1488] = 16'b1111110100001011;
assign imag_twiddles[1519:1504] = 16'b1111110100011100;
assign imag_twiddles[1535:1520] = 16'b1111110100101100;
assign imag_twiddles[1551:1536] = 16'b1111110100111101;
assign imag_twiddles[1567:1552] = 16'b1111110101001111;
assign imag_twiddles[1583:1568] = 16'b1111110101100001;
assign imag_twiddles[1599:1584] = 16'b1111110101110011;
assign imag_twiddles[1615:1600] = 16'b1111110110000110;
assign imag_twiddles[1631:1616] = 16'b1111110110011001;
assign imag_twiddles[1647:1632] = 16'b1111110110101101;
assign imag_twiddles[1663:1648] = 16'b1111110111000001;
assign imag_twiddles[1679:1664] = 16'b1111110111010101;
assign imag_twiddles[1695:1680] = 16'b1111110111101010;
assign imag_twiddles[1711:1696] = 16'b1111110111111110;
assign imag_twiddles[1727:1712] = 16'b1111111000010100;
assign imag_twiddles[1743:1728] = 16'b1111111000101001;
assign imag_twiddles[1759:1744] = 16'b1111111000111111;
assign imag_twiddles[1775:1760] = 16'b1111111001010101;
assign imag_twiddles[1791:1776] = 16'b1111111001101011;
assign imag_twiddles[1807:1792] = 16'b1111111010000010;
assign imag_twiddles[1823:1808] = 16'b1111111010011001;
assign imag_twiddles[1839:1824] = 16'b1111111010110000;
assign imag_twiddles[1855:1840] = 16'b1111111011000111;
assign imag_twiddles[1871:1856] = 16'b1111111011011110;
assign imag_twiddles[1887:1872] = 16'b1111111011110110;
assign imag_twiddles[1903:1888] = 16'b1111111100001110;
assign imag_twiddles[1919:1904] = 16'b1111111100100101;
assign imag_twiddles[1935:1920] = 16'b1111111100111101;
assign imag_twiddles[1951:1936] = 16'b1111111101010110;
assign imag_twiddles[1967:1952] = 16'b1111111101101110;
assign imag_twiddles[1983:1968] = 16'b1111111110000110;
assign imag_twiddles[1999:1984] = 16'b1111111110011110;
assign imag_twiddles[2015:2000] = 16'b1111111110110111;
assign imag_twiddles[2031:2016] = 16'b1111111111001111;
assign imag_twiddles[2047:2032] = 16'b1111111111101000;


endmodule