`default_nettype none

// DO NOT CHANGE ME. I AM AN AUTOGENERATED FILE

//-----------------------------------------------------------------------------
//  File       : twiddle.sv
//  Author     : Michael Ray
//  Created    : <2025-04-20>
//  Description: 
//      Stores the twiddle factors for an n point radix 2 fft
//
//  Parameters: None 
//
//  Ports:
//      Outputs:
//          - real_twiddles : array representing real components of twiddle factors
//          - imag_twiddles : array representing imaginary components of twiddle factors
//
//  Notes:
//      Do not attempt to modify this file. It was generated by the python script in the build module, "build.py"
//
//-----------------------------------------------------------------------------
module Twiddle_Coordinator #(
    parameter twiddle_size = 16,
    buffer_size = 32
) (
    output logic signed[(twiddle_size * buffer_size / 2) - 1:0] real_twiddles,
    output logic signed[(twiddle_size * buffer_size / 2) - 1:0] imag_twiddles
);

generate
    case(buffer_size)
		2 : Twiddle_Storage_2 twiddler (.real_twiddles(real_twiddles), .imag_twiddles(imag_twiddles));
		4 : Twiddle_Storage_4 twiddler (.real_twiddles(real_twiddles), .imag_twiddles(imag_twiddles));
		8 : Twiddle_Storage_8 twiddler (.real_twiddles(real_twiddles), .imag_twiddles(imag_twiddles));
		16 : Twiddle_Storage_16 twiddler (.real_twiddles(real_twiddles), .imag_twiddles(imag_twiddles));

    endcase
endgenerate

endmodule